name: covid
channels:
  - conda-forge
dependencies:
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-irkernel=1.1
  - conda-forge::r-ggplot2=3.3.0
  - conda-forge::r-cowplot=1.0.0
  - conda-forge::r-ggforce=0.3.1
  - conda-forge::r-base=3.6.2
  - conda-forge::r-ggrepel=0.8.1
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-leaflet=2.0.3
  - conda-forge::r-shiny=1.4.0.2
  - conda-forge::r-shinydashboard=0.7.1